### ISSUE TITLE
Data sources tab broken

### ISSUE THREAD

**Issue by wwieder** [lter/som-website#10]
I was told to update the data sources tab to use google sheets (4)?  not sure, but this seems like it broke the script that was reading from google drive folders.  @srearl this may not be critical, but could either be maintained or removed?

**Comment by srearl** [comment]
I am not sure that I am following. Are they suggesting that the data presented on the [Data sources](https://lter.github.io/som-website/data_sources.html) tab should in fact be in the form of an embedded Google Sheet or to just update the data? If the latter, I have not run the script for quite some time and it probably needs tweaking to accommodate new and updated Google API libraries but I can work on that.

**Comment by srearl** [comment]
Thanks @wwieder. Think we got it, the nav bar fields where rearranged only when a viewer was on the data_sources tab - still there just rearranged for whatever reason. Fixed.
