### ISSUE TITLE
QC plots

### ISSUE THREAD

**Issue by wwieder** [lter/som-website#2]
@brunj7 and @srearl .  I'm not sure how, but it seems like the QC plots have vanished (looks like the qaqc directory vanished).  This ended up not being as useful as I'd hoped, however, so maybe it doesn't really matter?

**Comment by wwieder** [comment]
@brunj7 I'd like to turn the projects page into a landing for different products that people are brainstorming with the database that can each have their own link.  I'm a little fuzzy on the best way of doing this and organizing the directory structure appropriately.  Suggestions are most welcome!

**Comment by srearl** [comment]
@wwieder the links needed to be updated and the page rebuilt since we moved the website to a different repo - went ahead and fixed this just in case these have some value going forward

cc @brunj7
